Fix distro detection

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -65,6 +65,22 @@ function print_runtime() {
 }
 trap print_runtime EXIT
 
+####################
+# Detect distro
+# Helpful link(s):
+# http://stackoverflow.com/questions/29581754
+# https://github.com/which-distro/os-release
+OS_RELEASE_FILE_CUSTOM="${REPO_ROOT}/os-release"
+if test -f "${OS_RELEASE_FILE_CUSTOM}"; then
+  printf "${STY_YELLOW}Warning: using custom os-release file \"${OS_RELEASE_FILE_CUSTOM}\".${STY_RST}\n"
+  OS_RELEASE_FILE="${OS_RELEASE_FILE_CUSTOM}"
+elif test -f /etc/os-release; then
+  OS_RELEASE_FILE=/etc/os-release
+else
+  printf "${STY_RED}/etc/os-release does not exist, aborting...${STY_RST}\n" ; exit 1
+fi
+export OS_DISTRO_ID=$(awk -F'=' '/^ID=/ { gsub("\"","",$2); print tolower($2) }' ${OS_RELEASE_FILE} 2> /dev/null)
+export OS_DISTRO_ID_LIKE=$(awk -F'=' '/^ID_LIKE=/ { gsub("\"","",$2); print tolower($2) }' ${OS_RELEASE_FILE} 2> /dev/null)
 #####################################################################################
 if [[ -f "${SUBCMD_DIR}/options.sh" ]];
   then source "${SUBCMD_DIR}/options.sh"
